name: flutter_sentinel
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  yaml: ^3.1.3
  dart_tabulate: ^1.0.0
  console_bars: ^1.2.0
  # cli_util: ^0.4.2
  # analyzer: ^5.13.0
  dcli: ^6.1.0
  args: ^2.6.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0